name: Build and Release macOS DMG

on:
  push:
    # Trigger on version tags like v1.2.3
    tags:
      - 'v*.*.*'

jobs:
  release-macos:
    name: Release macOS Universal DMG
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: |
            x86_64-apple-darwin
            aarch64-apple-darwin
          override: true

      - name: Install project dependencies
        run: npm ci

      - name: Build front-end and back-end
        run: npm run tauri-build -- --target universal-apple-darwin

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload DMG asset to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: src-tauri/target/universal-apple-darwin/release/bundle/dmg/ember-analysis_${{ github.ref_name }}.dmg
          asset_name: ember-analysis_${{ github.ref_name }}.dmg
          asset_content_type: application/x-apple-diskimage